@echo off

REM Remove temporary files generated by MPLAB X

echo Removing "*.X\build" directory...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.X"') do rd "%%i\build" /s /q
echo.

echo Removing "*.X\debug" directory...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.X"') do rd "%%i\debug" /s /q
echo.

echo Removing "*.X\disassembly" directory...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.X"') do rd "%%i\dist" /s /q
echo.

echo Removing "*.X\dist" directory...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.X"') do rd "%%i\disassembly" /s /q
echo.

echo Removing "*.X\nbproject\private" directory...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.X"') do rd "%%i\nbproject\private" /s /q
echo.

echo Removing "*.X\nbproject\*.mk" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.X"') do del "%%i\nbproject\*.mk" /f /q
echo.

echo Removing "*.X\nbproject\*.bash" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0\*.X"') do del "%%i\nbproject\*.bash" /f /q
echo.

echo Removing "*.X\nbproject\*.properties" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0\*.X"') do del "%%i\nbproject\*.properties" /f /q
echo.

echo Removing "*.X\nbproject\.dep.inc" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0\*.X"') do del "%%i\nbproject\.dep.inc" /f /q
echo.

echo Removing "*.X\nbproject\.map" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0\*.X"') do del "%%i\nbproject\.map" /f /q
echo.

echo "%~n0.bat" done.
