@echo off

REM Remove back up files generated by CircuitStudio in this directory and all subdirectories.

echo Removing "__Previews" directories recursively...
for /f "delims==" %%i in ('dir /ah /b /on /s "%~p0*__Previews"') do if "%%~ni"=="__Previews" rd "%%i" /s /q
echo.

echo Removing "History" directories recursively...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*History"') do if "%%~ni"=="History" rd "%%i" /s /q
echo.

echo Removing "Logs" directories recursively...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*Logs"') do if "%%~ni"=="Logs" rd "%%i" /s /q
echo.

echo Removing "Outputs" directories recursively...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*Outputs"') do if "%%~ni"=="Outputs" rd "%%i" /s /q
echo.

echo Removing "Project Logs for " directories recursively...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*Project Logs for *"') do rd "%%i" /s /q
echo.

echo Removing "*.PrjPcbStructure" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.PrjPcbStructure"') do del "%%i" /f /q
echo.

echo Removing "*.OutputStatus" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.OutputStatus"') do del "%%i" /f /q
echo.

echo Removing "*.drc" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.drc"') do del "%%i" /f /q
echo.

echo Removing "*.htm" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.htm"') do del "%%i" /f /q
echo.

echo Removing "*.html" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.html"') do del "%%i" /f /q
echo.

echo Removing "Status Report.Txt" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0Status Report.Txt"') do del "%%i" /f /q
echo.

echo Removing "*.APR_LIB" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.APR_LIB"') do del "%%i" /f /q
echo.

echo Removing "*.EXTREP" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.EXTREP"') do del "%%i" /f /q
echo.

echo Removing "*.REP" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.REP"') do del "%%i" /f /q
echo.

echo Removing "*.RUL" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.RUL"') do del "%%i" /f /q
echo.

echo Removing "*.apr" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.apr"') do del "%%i" /f /q
echo.

echo Removing "*.DRR" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.DRR"') do del "%%i" /f /q
echo.

echo Removing "*.LDP" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.LDP"') do del "%%i" /f /q
echo.

echo "%~n0.bat" done.
